name: "Setup Golang environment"
description: "A reusable workflow that's used to set up the Go environment and cache."
inputs:
  go-version:
    description: "The version of Golang to set up"
    required: true
  key-prefix:
    description: "A prefix to use for the cache key, to separate cache entries from other workflows"
    required: false

runs:
  using: "composite"

  steps:
    - name: set git config
      shell: bash
      run: |
        git config --global core.eol lf
        git config --global core.autocrlf false

    - name: setup go ${{ inputs.go-version }}
      uses: actions/setup-go@v5
      with:
        go-version: '${{ inputs.go-version }}'

    - name: set GOPATH
      shell: bash
      run: |
        echo "GOPATH=$(go env GOPATH)" >> $GITHUB_ENV
